#ifndef CUSTOM_DYNAMIC_ARRAY_LIB_CONSTANTS_H
#define CUSTOM_DYNAMIC_ARRAY_LIB_CONSTANTS_H

typedef enum ERROR_CODE {
    NOERROR=0,
    INVALID_ARRAY_ERROR=1,
    NULL_PTR_ERROR=2
} ERROR_CODE;

#endif // CUSTOM_DYNAMIC_ARRAY_LIB_CONSTANTS_H