name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Show compiler version
        run: gcc --version

      - name: Build and Unittests
        run: make test
      
      - name: Run Memory-tests
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
          valgrind --leak-check=full --error-exitcode=1 ./build/bin/test
